### ISSUE TITLE
feature request: sort by area

### ISSUE THREAD

**Issue by prankousky** [thomasloven/lovelace-auto-entities#138] opened 2020-09-17 14:35 UTC
Hi,

would this be possible? I am currently creating a `custom:auto-entities` card for **all** lights in the house. It would be nice if I could sort them by the area they are in. All lights have been assigned the appropriate area, so this should be possible if your card supported it.

I have tried

```
sort:
  method: area
```

But that does not work. Or is there a different approach that is already implemented to sort by room/area?

Thank you :)

**Comment by thomasloven** [comment] 2021-03-06 14:42
Duplicate of #47

**Closed by thomasloven** 2021-03-06 14:42 UTC
