### ISSUE TITLE
FR: Along with sorting have a "Group-By" option

### ISSUE THREAD

**Issue by danps1** [thomasloven/lovelace-auto-entities#254] opened 2022-02-25 23:26 UTC
Hi,
Love this card, and use it all over, so thanks very much!
One thing I think would be great would be having the ability to "Group-By" when sorting entities.
For example, I would have a filtered list of all of the lights in my house, but I would like to have them grouped by Area, so I'd see all the lights in a particular room listed together, and then the next room, and so on.
Thanks
Dan

**Comment by ildar170975** [comment] 2022-02-26 00:24
Alternatively you may specify a few filters (for each area) and sort each group separately.

**Comment by danps1** [comment] 2022-02-26 00:32
@ildar170975 true, but I might have 20 areas, so would need to do this 20 times over. And also if I added a new area it wouldn’t automatically be added to the card, so I’d have to go an manually update any cards.

**Comment by ildar170975** [comment] 2022-02-26 00:57
Then `template` option might be your choice

**Comment by danps1** [comment] 2022-02-26 01:14
I think `template` can be used as a filter, but not as part of a sort?
I don't need to alter the filtering, I have the right list of entities, I just want to enhance the way that they're sorted.

**Comment by thomasloven** [comment] 2022-03-11 21:25
Duplicate of #47

**Closed by thomasloven** 2022-03-11 21:25 UTC
