### ISSUE TITLE
Feature Request: Secondary Sorting Criteria

### ISSUE THREAD

**Issue by gregg098** [thomasloven/lovelace-auto-entities#135] opened 2020-08-20 15:38 UTC
Love the card and have been using it a lot. For one use case on an alternate dashboard, I use it a lot to see groups of all windows, lights, doors, etc. I recently started sorting by state so that the active entities move to the top of these lists, but the rest of the list is out of alphabetical order. Not a huge deal, but would be nice if there was a secondary sort option so that, in my case, I could sort by state, then by display name.

Thanks.

**Comment by thomasloven** [comment] 2021-03-06 14:42
Duplicate of #47

**Closed by thomasloven** 2021-03-06 14:42 UTC
