### ISSUE TITLE
Does not respect new "hidden" entity Advanced Option

### ISSUE THREAD

**Issue by nickh66** [thomasloven/lovelace-auto-entities#272] opened 2022-04-08 03:27 UTC
With the 2022.4 release there is now a new "switch at x" helper and the original switch entities can now be "hidden" from the UI.  However it seems these entities still show in my Dashboard.  I think some modification might be needed to either automatically 'exclude' any hidden entities or add a new filter option to exclude them.

**Comment by KrijnErmerins** [comment] 2022-04-11 06:15
This would be a great improvement!!

**Comment by sam-ward** [comment] 2022-04-23 08:20
I was going to log this as a feature request, as this would be extremely handy.

I had hoped that the "hidden" flag would have been exposed as an attribute on the entity (which we could then filter on), but it doesnt seem so.

**Comment by EDelsman** [comment] 2022-04-27 21:21
I would like a way to filter out hidden entities in the auto-entities card as well, and/or have it do so by default.

**Comment by tboyce021** [comment] 2022-04-28 04:20
I would vote for just excluding them by default. To me, auto-entities is essentially part of a DIY auto generated dashboard (just in card form) and I imagine the whole point of the "hidden" option is to keep things out of auto generated dashboards. However, if that creates more problems than it solves then I wouldn't complain about an extra filter option to handle it.

**Comment by bjeanes** [comment] 2022-04-29 22:05
Duplicate of #270 but +1

**Comment by VimalO** [comment] 2022-08-27 18:59
Would be a useful feature to be able to exclude those hidden entitites

**Comment by JSteeleIR** [comment] 2022-09-09 07:09
Would love to see progress on this.

I have several entities that I've now use the "show as X" helper on, and they show up as "duplicates" in my auto-entities populated cards, with no seeming way to filter them out.

**Comment by vdbrink** [comment] 2022-10-19 19:22
I can't remove some items from HA only hide them. It will be very nice to exclude them here also.

**Comment by teskanoo** [comment] 2022-12-27 03:13
Thank you for addressing this feature request in the latest release :)

**Comment by thomasloven** [comment] 2022-12-27 09:52
Fixed by #277

**Closed by thomasloven** 2022-12-27 09:52 UTC
