### ISSUE TITLE
[Feature Request] Filter by entity_category

### ISSUE THREAD

**Issue by diplix** [thomasloven/lovelace-auto-entities#233] opened 2021-11-24 09:08 UTC
Would it be possible to add a filter for the new(ish) [entity category](https://developers.home-assistant.io/docs/core/entity/#generic-properties) (system, configuration, diagnostic)?

**Comment by thomasloven** [comment] 2022-02-19 23:36
Duplicate of #227

**Closed by thomasloven** 2022-02-19 23:36 UTC
